version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ${CONTAINER_NAME}
    restart: always
    ports:
        - "${APP_PORT}:80"
    volumes:
      - codebase:/var/www/html/
      - storage:/var/www/html/storage
      - public_uploads:/var/www/html/public/uploads
      - public_storage:/var/www/html/public/storage
    networks:
      - network

volumes:
  codebase:
  storage:
  public_uploads:
  public_storage:

networks:
  network:
